// app/hirex/ethics-policy/page.tsx

'use client';

import React, { useState } from 'react';
import Navbar from '@/components/hirex/layout/Navbar';
import Footer from '@/components/hirex/home/Footer';
import { 
  Scale, HeartHandshake, Eye, UserCheck, 
  ShieldAlert, MessageSquare, Gavel, 
  CheckCircle2, X, Send, ArrowRight,
  BrainCircuit, AlertCircle, ScanFace
} from 'lucide-react';

const ETHICS_PILLARS = [
  {
    title: "Zero-Bias Architecture",
    desc: "Our Gemini AI engine strips all demographic identifiers (names, gender, age, ethnicity) before evaluation. Candidates are scored purely on logic, code quality, and system design.",
    icon: Scale,
    color: "text-sky-400",
    bg: "bg-sky-500/10",
    border: "border-sky-500/30"
  },
  {
    title: "Explainable AI (XAI)",
    desc: "We do not believe in 'black box' hiring. Every technical score generated by HireX is accompanied by a transparent, human-readable breakdown of the AI's reasoning.",
    icon: Eye,
    color: "text-violet-400",
    bg: "bg-violet-500/10",
    border: "border-violet-500/30"
  },
  {
    title: "Human-in-the-Loop",
    desc: "HireX acts as an autonomous technical screener, but the final hiring decision ALWAYS rests with a human. We augment HR teams; we do not replace human judgment.",
    icon: UserCheck,
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30"
  },
  {
    title: "Continuous Auditing",
    desc: "Our neural networks undergo rigorous, continuous third-party audits to detect and mitigate any emerging biases in our evaluation matrices.",
    icon: ShieldAlert,
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30"
  }
];

export default function EthicsPolicyPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [formData, setFormData] = useState({ name: '', email: '', category: 'Algorithm Bias Concern', message: '' });

  const handleWhatsAppSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const phoneNumber = "918700236923";
    const message = `*HireX AI Ethics Report*%0A%0A*Name:* ${formData.name}%0A*Email:* ${formData.email}%0A*Category:* ${formData.category}%0A*Details:* ${formData.message}%0A%0A_Please route this to the AI Ethics Board._`;
    
    window.open(`https://wa.me/${phoneNumber}?text=${message}`, '_blank');
    setIsModalOpen(false);
    setFormData({ name: '', email: '', category: 'Algorithm Bias Concern', message: '' });
  };

  return (
    <main className="min-h-screen relative overflow-hidden bg-[#020617] text-white selection:bg-sky-500/30 font-sans">
      
      {/* Calm & Trustworthy Background Ambience */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute top-0 left-0 w-[500px] md:w-[900px] h-[500px] md:h-[900px] bg-sky-600/10 blur-[150px] rounded-full -translate-x-1/4 -translate-y-1/4" />
        <div className="absolute bottom-0 right-0 w-[400px] md:w-[700px] h-[400px] md:h-[700px] bg-violet-600/10 blur-[120px] rounded-full translate-x-1/4 translate-y-1/4" />
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px] opacity-20" />
      </div>

      <Navbar />

      <div className="relative z-10 pt-28 pb-16 md:pt-40 md:pb-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          
          {/* Header Section */}
          <div className="max-w-4xl mx-auto text-center mb-16 md:mb-24 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-sky-500/10 border border-sky-500/30 text-sky-400 text-[10px] md:text-xs font-mono uppercase tracking-widest mb-6 shadow-[0_0_20px_rgba(14,165,233,0.2)]">
              <HeartHandshake className="w-3.5 h-3.5 md:w-4 md:h-4" /> Responsible Automation
            </div>
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-black tracking-tight mb-6 leading-tight">
              AI Ethics & <span className="text-white bg-clip-text bg-gradient-to-r from-sky-400 to-violet-400">Fairness Policy</span>
            </h1>
            <p className="text-sm md:text-xl text-slate-400 leading-relaxed max-w-2xl mx-auto">
              Technology should democratize opportunity, not automate inequality. Read our core manifesto on how we ensure fairness, transparency, and human dignity in algorithmic hiring.
            </p>
          </div>

          {/* Ethics Pillars Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-20 md:mb-32">
            {ETHICS_PILLARS.map((pillar, idx) => (
              <div key={idx} className="bg-slate-900/40 backdrop-blur-xl border border-white/10 rounded-[2rem] p-8 md:p-10 hover:bg-slate-900/60 transition-colors group relative overflow-hidden">
                <div className={`absolute -right-10 -bottom-10 w-40 h-40 ${pillar.bg} blur-3xl rounded-full opacity-30 group-hover:opacity-60 transition-opacity`} />
                <div className={`w-12 h-12 md:w-14 md:h-14 rounded-2xl ${pillar.bg} border ${pillar.border} flex items-center justify-center mb-6 relative z-10`}>
                  <pillar.icon className={`w-6 h-6 md:w-7 md:h-7 ${pillar.color}`} />
                </div>
                <h3 className="text-xl md:text-2xl font-bold text-white mb-3 relative z-10">{pillar.title}</h3>
                <p className="text-slate-400 text-sm md:text-base leading-relaxed relative z-10">{pillar.desc}</p>
              </div>
            ))}
          </div>

          {/* Detailed Policy Articles */}
          <div className="bg-[#0b0f1f]/80 backdrop-blur-2xl border border-sky-500/20 rounded-[2rem] md:rounded-[3rem] p-8 md:p-16 mb-20 md:mb-32 shadow-[0_0_50px_rgba(14,165,233,0.1)]">
            <div className="prose prose-invert max-w-none space-y-12">
              
              <section>
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-10 h-10 rounded-full bg-sky-500/20 flex items-center justify-center shrink-0">
                    <ScanFace className="w-5 h-5 text-sky-400" />
                  </div>
                  <h2 className="text-2xl md:text-3xl font-black text-white m-0">Article 1: Blind Evaluation Protocols</h2>
                </div>
                <p className="text-slate-400 leading-relaxed">
                  HireX operates on a strict "Blind Evaluation" framework. When a candidate submits code or answers technical questions, the AI is explicitly restricted from accessing metadata that could indicate gender, race, age, educational pedigree, or geographic location. 
                  <br /><br />
                  The Neural Ledger logs only logical operators, Big-O time complexity, syntax cleanliness, and system architecture decisions. This guarantees that candidates from non-traditional backgrounds (e.g., self-taught developers, bootcamps) are evaluated on the exact same scale as Ivy League graduates.
                </p>
              </section>

              <hr className="border-white/10" />

              <section>
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-10 h-10 rounded-full bg-violet-500/20 flex items-center justify-center shrink-0">
                    <AlertCircle className="w-5 h-5 text-violet-400" />
                  </div>
                  <h2 className="text-2xl md:text-3xl font-black text-white m-0">Article 2: Candidate Recourse & Appeals</h2>
                </div>
                <p className="text-slate-400 leading-relaxed">
                  No algorithm is flawless. If a candidate believes their technical assessment was misgraded or an anti-cheat protocol was triggered in error, HireX guarantees the <strong>Right to Appeal</strong>.
                </p>
                <ul className="mt-6 space-y-4">
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-violet-400 mt-0.5 shrink-0" />
                    <span className="text-slate-300">Candidates can trigger a manual review of their Neural Ledger transcript.</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-violet-400 mt-0.5 shrink-0" />
                    <span className="text-slate-300">Appeals are reviewed by human engineers, bypassing the AI entirely.</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-violet-400 mt-0.5 shrink-0" />
                    <span className="text-slate-300">Employers are notified if an AI decision is successfully overturned.</span>
                  </li>
                </ul>
              </section>

              <hr className="border-white/10" />

              <section>
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                    <BrainCircuit className="w-5 h-5 text-emerald-400" />
                  </div>
                  <h2 className="text-2xl md:text-3xl font-black text-white m-0">Article 3: Generative AI Limitations</h2>
                </div>
                <p className="text-slate-400 leading-relaxed">
                  We utilize Google's Gemini 2.5 Flash API for our core assessments. We acknowledge the inherent risks of LLM hallucinations. Therefore, HireX does not use Generative AI to make <em>final</em> hiring decisions. It is strictly deployed as an assessment layer to quantify technical depth, providing HR professionals with verified data points to make informed, human-led decisions.
                </p>
              </section>

            </div>
          </div>

          {/* Contact Board Banner */}
          <div className="max-w-5xl mx-auto p-8 md:p-14 rounded-[2rem] md:rounded-[3rem] bg-gradient-to-br from-sky-900/40 to-slate-900 border border-sky-500/30 flex flex-col md:flex-row items-center justify-between gap-8 shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-sky-500/10 blur-[100px] rounded-full pointer-events-none" />
            
            <div className="relative z-10 text-center md:text-left max-w-xl">
              <h2 className="text-2xl md:text-4xl font-black text-white mb-4">Have an ethical concern?</h2>
              <p className="text-sky-100 text-sm md:text-base leading-relaxed">
                If you have experienced algorithmic bias, or if you are a researcher wanting to audit our methodology, our AI Ethics Board wants to hear from you.
              </p>
            </div>
            
            <button 
              onClick={() => setIsModalOpen(true)}
              className="relative z-10 w-full md:w-auto px-8 py-4 bg-sky-600 hover:bg-sky-500 text-white font-black rounded-2xl hover:scale-105 transition-transform shadow-[0_10px_40px_rgba(14,165,233,0.3)] flex items-center justify-center gap-2"
            >
              Report a Concern <Gavel className="w-5 h-5" />
            </button>
          </div>

        </div>
      </div>

      {/* AI ETHICS REPORT MODAL */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-300">
          <div className="relative w-full max-w-lg bg-[#0b0f1f] border border-sky-500/30 rounded-[2rem] overflow-hidden shadow-[0_0_50px_rgba(14,165,233,0.15)]">
            <button onClick={() => setIsModalOpen(false)} className="absolute top-6 right-6 p-2 text-slate-500 hover:text-white transition-colors bg-white/5 rounded-full z-10">
              <X className="w-5 h-5" />
            </button>
            
            <div className="p-8 md:p-10 relative">
              <div className="absolute -top-20 -left-20 w-40 h-40 bg-sky-500/20 blur-3xl rounded-full" />
              
              <div className="mb-8 text-center relative z-10">
                <div className="w-16 h-16 bg-sky-500/10 text-sky-400 rounded-2xl flex items-center justify-center mx-auto mb-4 border border-sky-500/20">
                  <Scale className="w-8 h-8" />
                </div>
                <h3 className="text-2xl font-bold">AI Ethics Board</h3>
                <p className="text-slate-400 text-sm mt-1">Submit your concern directly to our committee.</p>
              </div>

              <form onSubmit={handleWhatsAppSubmit} className="space-y-4 relative z-10">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="relative">
                    <input 
                      required type="text" placeholder="Your Name"
                      className="bg-white/5 border border-white/10 rounded-xl p-4 text-sm focus:border-sky-500 outline-none w-full"
                      value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})}
                    />
                  </div>
                  <div className="relative">
                    <input 
                      required type="email" placeholder="Your Email"
                      className="bg-white/5 border border-white/10 rounded-xl p-4 text-sm focus:border-sky-500 outline-none w-full"
                      value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})}
                    />
                  </div>
                </div>

                <div className="relative">
                  <select 
                    className="bg-white/5 border border-white/10 rounded-xl p-4 text-sm text-slate-300 focus:border-sky-500 outline-none w-full appearance-none"
                    value={formData.category} onChange={e => setFormData({...formData, category: e.target.value})}
                  >
                    <option value="Algorithm Bias Concern" className="bg-slate-900">Algorithm Bias Concern</option>
                    <option value="Appeal Assessment Score" className="bg-slate-900">Appeal Assessment Score</option>
                    <option value="Accessibility Issue" className="bg-slate-900">Accessibility Issue</option>
                    <option value="Research & Audit Request" className="bg-slate-900">Research & Audit Request</option>
                  </select>
                </div>

                <div className="relative">
                  <textarea 
                    required placeholder="Please provide details of your concern..." rows={4}
                    className="bg-white/5 border border-white/10 rounded-xl p-4 text-sm focus:border-sky-500 outline-none w-full resize-none"
                    value={formData.message} onChange={e => setFormData({...formData, message: e.target.value})}
                  />
                </div>
                
                <button 
                  type="submit"
                  className="w-full bg-sky-600 hover:bg-sky-500 text-white font-black py-4 rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-sky-900/40 mt-6"
                >
                  Submit to Ethics Board <Send className="w-4 h-4" />
                </button>
                <p className="text-[10px] text-center text-slate-500 uppercase tracking-widest font-mono mt-4">Routed directly to: +91 870023 6923</p>
              </form>
            </div>
          </div>
        </div>
      )}

      <Footer />

      <style jsx global>{`
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
      `}</style>
    </main>
  );
}