"use client";

import React from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/sections/Footer';
import { BookOpen, Clock, Award, ShieldAlert, FileText, Mail, CheckCircle } from 'lucide-react';
import { usePageContent } from '@/hooks/usePageContent';

const ExaminationPolicy = () => {
  const { get } = usePageContent('home-examination');

  // ── Hero ──────────────────────────────────────────────────────────────────
  const accentFrom        = get('hero', 'accent_from',     '#3b82f6');
  const accentTo          = get('hero', 'accent_to',       '#6366f1');
  const badgeText         = get('hero', 'badge_text',      'Academic Integrity');
  const headlinePlain     = get('hero', 'headline_plain',  'Examination');
  const headlineAccent    = get('hero', 'headline_accent', 'Policy.');
  const lastUpdated       = get('hero', 'last_updated',    'October 24, 2023');

  // ── Assessment Standards ──────────────────────────────────────────────────
  const assessTitle       = get('assessment', 'section_title', 'Assessment Standards');
  const assessBody        = get('assessment', 'body_text',     'Our examination policy ensures a fair, consistent, and rigorous evaluation of all students. By participating in our assessments, you agree to adhere to the code of conduct and technical requirements outlined below. These standards are designed to maintain the prestige of our certifications.');

  // ── Code of Conduct ───────────────────────────────────────────────────────
  const conductTitle      = get('conduct', 'section_title',  'Code of Conduct');
  const conductIntro      = get('conduct', 'intro_text',     'Academic honesty is paramount. The following actions are strictly prohibited during any examination:');
  const conductBullet1    = get('conduct', 'bullet_plagiarism',   'Submission of work that is not entirely your own or generated by unauthorized AI tools.');
  const conductBullet2    = get('conduct', 'bullet_collab',       'Communicating with other candidates or external parties during live assessments.');
  const conductBullet3    = get('conduct', 'bullet_materials',    'Using unauthorized books, notes, or digital resources unless explicitly permitted.');
  const conductBullet4    = get('conduct', 'bullet_violation',    'Any breach of these rules may lead to immediate disqualification without a refund.');

  // ── Technical Requirements ────────────────────────────────────────────────
  const techTitle         = get('technical', 'section_title', 'Technical Requirements');
  const techCard1Title    = get('technical', 'card1_title',   'System Stability');
  const techCard1Body     = get('technical', 'card1_body',    'Ensure a stable internet connection. We are not responsible for progress lost due to local hardware or network failures.');
  const techCard2Title    = get('technical', 'card2_title',   'Timed Sessions');
  const techCard2Body     = get('technical', 'card2_body',    'Exams must be completed within the allotted time. Once the timer expires, your current progress will be auto-submitted.');

  // ── Results ───────────────────────────────────────────────────────────────
  const resultsTitle      = get('results', 'section_title', 'Passing Criteria & Results');
  const resultsBullet1    = get('results', 'bullet_score',    'Minimum passing score is 70% unless stated otherwise.');
  const resultsBullet2    = get('results', 'bullet_release',  'Results are typically processed and released within 3 to 5 business days.');
  const resultsBullet3    = get('results', 'bullet_retake',   'Retake opportunities are subject to a mandatory 7-day cooling-off period.');

  // ── Contact ───────────────────────────────────────────────────────────────
  const contactNote       = get('contact', 'note_text',     'For technical issues during an exam or to appeal a grading decision, please contact our academic board.');
  const contactCTA        = get('contact', 'cta_headline',  'Dispute?');
  const contactSubtext    = get('contact', 'subtext',       'Submit an appeal request via email:');
  const contactEmail      = get('contact', 'email_address', 'exams@yourdomain.com');
  const contactBtnLabel   = get('contact', 'btn_label',     'Contact Registrar');

  return (
    <main className="min-h-screen bg-[#020617] text-slate-100 font-sans">
      <Navbar />

      {/* Hero */}
      <section className="pt-32 pb-16 px-6 border-b border-white/5 bg-slate-900/20">
        <div className="max-w-4xl mx-auto">
          <div
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full mb-6 backdrop-blur-xl"
            style={{ background: `${accentFrom}1a`, border: `1px solid ${accentFrom}33` }}
          >
            <BookOpen size={14} style={{ color: accentFrom }} />
            <span className="text-[10px] font-black uppercase tracking-[0.2em]" style={{ color: accentFrom }}>
              {badgeText}
            </span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase italic mb-4">
            {headlinePlain} <span className="text-slate-500">{headlineAccent}</span>
          </h1>
          <p className="text-slate-400 font-light italic text-sm">Last Updated: {lastUpdated}</p>
        </div>
      </section>

      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto space-y-16">

          {/* Assessment Standards */}
          <article className="space-y-6">
            <div className="flex items-center gap-3" style={{ color: accentFrom }}>
              <FileText size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">{assessTitle}</h2>
            </div>
            <p className="text-slate-400 leading-relaxed font-light">{assessBody}</p>
          </article>

          {/* Code of Conduct */}
          <article
            className="p-8 rounded-[2rem] space-y-6"
            style={{ background: '#ef44440d', border: '1px solid #ef444433' }}
          >
            <div className="flex items-center gap-3 text-red-400">
              <ShieldAlert size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">{conductTitle}</h2>
            </div>
            <div className="space-y-4 text-slate-400 leading-relaxed font-light">
              <p>{conductIntro}</p>
              <ul className="list-disc pl-6 space-y-3 marker:text-blue-500">
                <li><strong>Plagiarism:</strong> {conductBullet1}</li>
                <li><strong>Collaboration:</strong> {conductBullet2}</li>
                <li><strong>External Materials:</strong> {conductBullet3}</li>
                <li><strong>Violation:</strong> {conductBullet4}</li>
              </ul>
            </div>
          </article>

          {/* Technical Requirements */}
          <article className="space-y-6">
            <div className="flex items-center gap-3" style={{ color: accentFrom }}>
              <Clock size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">{techTitle}</h2>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/5">
                <h4 className="text-white font-bold text-sm mb-2 uppercase italic tracking-wider">{techCard1Title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed">{techCard1Body}</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/5">
                <h4 className="text-white font-bold text-sm mb-2 uppercase italic tracking-wider">{techCard2Title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed">{techCard2Body}</p>
              </div>
            </div>
          </article>

          {/* Results */}
          <article className="space-y-6">
            <div className="flex items-center gap-3" style={{ color: accentFrom }}>
              <Award size={20} />
              <h2 className="text-xl font-black uppercase tracking-tight italic text-white">{resultsTitle}</h2>
            </div>
            <div className="space-y-4 text-slate-400 leading-relaxed font-light">
              {[resultsBullet1, resultsBullet2, resultsBullet3].map((b, i) => (
                <p key={i} className="flex items-center gap-2">
                  <CheckCircle size={14} style={{ color: accentFrom, flexShrink: 0 }} />
                  {b}
                </p>
              ))}
            </div>
          </article>

          {/* Contact */}
          <article className="pt-10 border-t border-white/5">
            <div className="flex flex-col md:flex-row justify-between gap-10">
              <div className="space-y-4 max-w-sm">
                <div className="flex items-center gap-2 text-white font-black italic uppercase">
                  <Mail size={16} />
                  <span>Exam Registrar</span>
                </div>
                <p className="text-sm text-slate-500 font-light">{contactNote}</p>
              </div>
              <div className="space-y-4">
                <h3 className="text-white font-black italic uppercase tracking-tighter text-2xl">{contactCTA}</h3>
                <p className="text-slate-400 text-sm mb-4">{contactSubtext}</p>
                <button
                  onClick={() => window.location.href = `mailto:${contactEmail}`}
                  className="bg-white text-black px-8 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest transition-all"
                  onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = accentFrom; (e.currentTarget as HTMLButtonElement).style.color = '#fff'; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#fff'; (e.currentTarget as HTMLButtonElement).style.color = '#000'; }}
                >
                  {contactBtnLabel}
                </button>
              </div>
            </div>
          </article>

        </div>
      </section>

      <Footer />
    </main>
  );
};

export default ExaminationPolicy;